# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
