# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_driver_isonline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='isOnline',
            new_name='is_online',
        ),
        migrations.AddField(
            model_name='driver',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
